export default {
  GET_CHANNELS: "GET_CHANNELS",
  GET_CHANNEL: "GET_CHANNEL",
  CLEAR_CHANNEL: "CLEAR_CHANNEL",
  GET_CHANNEL_LOG_HOUR : "GET_CHANNEL_LOG_HOUR",
  GET_CHANNEL_LOG_DAY : "GET_CHANNEL_LOG_DAY",
}
